# Generated by Django 4.2.16 on 2024-09-23 21:32

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_published_date_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
