# Generated by Django 4.2.16 on 2024-09-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Product Review', 'Product Review'), ('Tips and Tricks', 'Tips and Tricks'), ('No Category', 'No Category')], default='No Category', max_length=50),
        ),
    ]
